# Workflow for building and testing the Python code.
# https://docs.github.com/en/actions/guides/building-and-testing-python

name: Python build

on:
  pull_request:
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }} on ${{ matrix.os }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install yapf pylint pyright pytest pytest-custom_exit_code
        if [[ -f setup.cfg ]]; then python -m pip install -e .; fi
    - name: Check formatting with yapf
      if: ${{ always() }}
      run: |
        yapf . --diff --recursive --parallel
    - name: Lint with pylint
      if: ${{ always() }}
      run: |
        pylint $(git ls-files '*.py')
    - name: Type checking with pyright
      if: ${{ always() }}
      run: |
        pyright
    - name: Test with pytest
      if: ${{ always() }}
      run: |
        pytest --suppress-no-test-exit-code
